### ISSUE TITLE
Fatal error: Can't use function return value in write context in /oc/common/classes/controller/panel/user.php

### ISSUE THREAD

**Issue by AndreasRicci** [open-classifieds/common#108]
This occurred using OpenClassifieds2 master.

The problem is described here: http://stackoverflow.com/questions/1532693/weird-php-error-cant-use-function-return-value-in-write-context

Fix: https://github.com/open-classifieds/common/pull/107

**Comment by neo22s** [comment]
Thanks anyway andreas :)

**Comment by AndreasRicci** [comment]
No problem, always happy to (try) to help!

**Comment by neo22s** [comment]
You do good! its great to get people involved!! we apreciate it a lot.
